services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    env_file: "./src/main/resources/.env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: spring-all
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"  # REST API
      - "9300:9300"  # Cluster communication
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data