services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: spring-all
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch-container
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      xpack.security.http.ssl.enabled: false
      xpack.license.self_generated.type: trial
    ports:
      - "9200:9200"  # REST API
      - "9300:9300"  # Cluster communication
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka-broker-container
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/lib/kafka/data

  consul-server:
    image: hashicorp/consul:1.15.4
    container_name: consul-server-container
    ports:
      - "8300:8300/tcp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8500:8500/tcp"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./data/consul/server.json:/consul/config/server.json
      - ./data/consul/certs:/consul/config/certs/:ro

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-container
    ports:
      - "9411:9411"
    volumes:
      - ./data/zipkin:/zipkin/data