server:
  port: 8081


spring:
  config:
    import:
      - "optional:configserver:"
  application:
    name: microservice-product
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true
          ttl: 10s



  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml